### PR TITLE
[PECO-163] Update GoLang clients' user agent

### PR DESCRIPTION
**Pull request by yunbodeng-db**
Update user agent of GoLang client.

### CODE REVIEW

**Comment by yunbodeng-db** [comment]
I will not submit until the server code is live ~June 27th.

**Comment by yunbodeng-db** [comment]
All servers have been updated. Now I can submit this PR.

**Comment by yunbodeng-db** [comment]
Ping @arikfr and @susodapop ...

**Review by susodapop — APPROVED** [review]
LGTM

**Comment by yunbodeng-db** [comment]
jenkins merge

**Pull request merged**
