### PR TITLE
feat: Update Apache Arrow to `v16`

### PR DESCRIPTION
**Pull request by candiduslynx**
Instead of https://github.com/databricks/databricks-sql-go/pull/209

### CODE REVIEW

**Comment by candiduslynx** [comment]
@kravets-levko would you mind also reviewing this PR & releasing afterwards?
I've been using a fork at https://github.com/cloudquery/databricks-sql-go (`cqmain` branch) with #216 & #217 merged into to achieve everything required for the code I'm developing.

The major bump to `v15` just updates the library code, the underlying arrow data (wire protocol) stays the same.

**Comment by kravets-levko** [comment]
@candiduslynx I totally understand your need in this upgrade, however I'm a bit new to this project in particular and Go language in general. So I need @andrefurlan-db or @rcypher-databricks approval, and then I'll merge and ship this change. Sorry, and thank you for understanding

**Comment by yunbodeng-db** [comment]
@andrefurlan-db can you help out on this one?

**Review by kravets-levko — APPROVED** [review]

**Comment by candiduslynx** [comment]
@kravets-levko thanks for the review!
Is there a way to expedite the merge & release of this code along with #207?

**Comment by kravets-levko** [comment]
@candiduslynx databricks/databricks-sql-go#207 should be available in v1.5.4. For this PR - I think I'll add it to the next release, hopefully will be available on Monday-Tuesday

**Comment by kravets-levko** [comment]
@candiduslynx sorry for a bad news, but turns out that Arrow upgrade caused issues for library users. Library offers a feature that allows to access raw Arrow batches, and with this upgrade behavior of that feature changed. After discussion with other team members, we decided to revert this upgrade for now

**Comment by candiduslynx** [comment]
@kravets-levko thanks for notifying!
I think you need to add some tests to outline the expected behaviour then.
However, I wonder what are the details of the changed behaviour that isn't deemed correct by clients? Is it just a requirement to update the library?

**Pull request merged**
