### PR TITLE
Revert update Apache Arrow to `v16`

### PR DESCRIPTION
**Pull request by kravets-levko**
Reverts databricks/databricks-sql-go#216

Unfortunately, updating Apache Arrow turned out to be a breaking change which created issues to some library users. We made a decision to revert this upgrade

### CODE REVIEW

**Review by yunbodeng-db — APPROVED** [review]

**Comment by candiduslynx** [comment]
Hi @kravets-levko!
Is there any issue to track the upgrade of the library, as this got reverted?
Basically, is there a plan & outlined steps to roll the arrow/v16 once again?

**Comment by kravets-levko** [comment]
Hi @candiduslynx! Yes, we indeed plan to re-do the upgrade at some point. But we are looking for the way to do this and avoid issues for our users. We don't expect any major changes to the library, so you can continue using `v1.5.5` for now. I'm sorry for all this, but please be patient, once we'll figure things out - I will let you know

**Comment by datbth** [comment]
Is there any place that mentions the breaking changes?
So that we (as users) are aware of the issues when forking/upgrading ourselves?

**Comment by candiduslynx** [comment]
Is this still on v12?
Wow, what a shame.

**Pull request merged**
