### PR TITLE
Fix Spark parameter creation when passing a `nil`-value named parameter to a query 

### LINKED ISSUE #193: Issue while converting `nil` SQL parameter to `null`
I was trying to use a query like this. I expected my query to return all results if it's not filtered, and filter the result if there's a filter.

```sql
SELECT *
FROM some_table
WHERE ISNULL(:mmCode) OR name = :mmCode
```

and then I pass `sql.Named("mmCode", code)` to my query.
`code` is a `*string`. It can, of course, be nil.

## Expected behaviour

- If `name` is `nil`, then it would be converted to `NULL` in SQL and trigger the first case in my `WHERE` clause.
- If `name` is not `nil`, then it would become a string and trigger the second case in my `WHERE` clause.

## Actual behaviour

I noticed that the library tries to use `fmt.Sprintf("%s", param.Value)` in [parameters.go](https://github.com/databricks/databricks-sql-go/blob/main/parameters.go#L136-L139). If `param.Value` is `nil`, it becomes `"%s(<nil>)"` and my query won't work.

image

## Workaround

I'm now manually creating my `WHERE` clause depending of the values I have for each filter parameter, but being able to use `ISNULL` would and inject `nil` parameters make my code shorter and cleaner.

I tried to write a PR myself, but I'm not familiar with the Spark parameters API.

### PR DESCRIPTION
**Pull request by esdrasbeleza**
- When a `sql.NamedValue` has the field `Value` set to `nil`, the resulting `cli_service.TSparkParameter` will also have the value `nil` instead of `*cli_service.TSparkParameterValue{StringValue: *"%!s(<nil>"}`.
- Add the type `SqlVoid`, following the conventions used in the [NodeJS connector](https://github.com/databricks/databricks-sql-nodejs/blob/main/lib/DBSQLParameter.ts#L43-L51) and the [Python driver](https://github.com/databricks/databricks-sql-python/blob/f6fd7a7956a4dbc78ad36b5e079fe8d74176a0f1/src/databricks/sql/parameters/native.py#L319-L323).

Fix #193.

### CODE REVIEW

**Review by kravets-levko — APPROVED** [review]
LGTM 👍 Though, better if someone of codeowners make a final decision

**Comment by kravets-levko** [comment]
@esdrasbeleza Can you please rebase and resolve conflicts? Thanks!

**Comment by esdrasbeleza** [comment]
@kravets-levko got a bit lost in the process with merges, rebases, signoffs etc., but it's done 😅 
10+ years of git and it's never enough!

**Comment by kravets-levko** [comment]
@esdrasbeleza Merged 👍 I'd like to ship one more PR with this release - waiting for a person to rebase their branch and we're good to go. After that I'll cut a release ASAP

**Pull request merged**
